name: release
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag }}
    permissions:
      contents: write
      pull-requests: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0' # with tags, required for release
    - uses: bboughton/example-action@5bdd288f1ff7350a6d4b36c57296872e6aeaec12
      id: release

#   publish:
#     needs: if_merged
#     uses: ./.github/workflows/publish.yml
#     with:
#       tag: ${{ needs.if_merged.outputs.tag }}
#     secrets: inherit
