name: triage
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_version_category_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3
    - uses: bboughton/example-action/check-version-category-label@fa1285f4703e1eed67560c6ac1900e8a956627e6
