name: triage
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_version_category_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3
    - uses: bboughton/example-action/check-version-category-label@5bdd288f1ff7350a6d4b36c57296872e6aeaec12
