name: triage
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_version_category_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - uses: actions/checkout@v3
    - uses: bboughton/example-action/check-version-category-label@7832a327466cca63349f42711941f73f21ca7c66
